spring:
  # Cloud Stream
  cloud:
    stream:
      rabbit.bindings:
        asyncSupplier-out-0:
          producer:
            bindingRoutingKey: demo.async
            routingKeyExpression: '''demo.async'''
        syncSupplier-out-0:
          producer:
            bindingRoutingKey: demo.sync
            routingKeyExpression: '''demo.sync'''
      bindings:
        asyncSupplier-out-0:
          destination: demo
          content-type: application/json
          producer.requiredGroups: demo.async
        syncSupplier:
          destination: demo
          content-type: application/json
          producer.requiredGroups: demo.sync
    function:
      definition: asyncSupplier

  # RabbitMQ
  rabbitmq:
    host: 192.168.100.131
    port: 5672
    username: financial
    password: financial

# Logging properties
logging:
  level:
    org.springframework.cloud.function.context.catalog.BeanFactoryAwareFunctionRegistry: warn
